### ISSUE TITLE
All themes page

### ISSUE THREAD

**Issue by csszen** [CSS-ZEN/garden#12]
Consider graphql requests used in fetching theme choices. A page displaying theme with more informations:

- screenshot: maybe we need a service to crawl screenshots when sites generated, this service had better to be standalone
- statistics: information like stars is available in the graphql responses, maybe we need service to track view logs and collect lighthouse report and attach to the gists

Since the services are unavailable currently, maybe we can draw a draft page first.

**Comment by somarlyonks** [comment]
A draft #24 was merged. We'd better to fallback to iframe render if screenshot is unavailable or find transition/animation in theme.

Anyway, it looks good to me to close this issue.
