### ISSUE TITLE
Copy more themes from original project

### ISSUE THREAD

**Issue by csszen** [CSS-ZEN/garden#14]

**Comment by somarlyonks** [comment]
I traversed all original themes and picked these I think worth migrating:

- [ ] 221
- [ ] 218
- [ ] 214
- [ ] 213
- [ ] 209
- [ ] 207
- [ ] 203
- [ ] 201
- [ ] 198
- [ ] 193
- [ ] 184
- [ ] 181
- [ ] 179
- [ ] 177
- [ ] 176
- [ ] 173
- [ ] 171
- [ ] 159
- [ ] 153
- [ ] 152
- [ ] 151
- [ ] 145
- [ ] 143
- [ ] 142
- [ ] 139
- [ ] 137
- [ ] 135
- [ ] 130
- [ ] 127
- [ ] 122
- [ ] 120
- [ ] 118
- [ ] 113
- [ ] 111
- [ ] 107
- [ ] 105
- [ ] 104
- [ ] 103
- [ ] 102
- [ ] 101
- [ ] 099
- [ ] 097
- [ ] 089
- [ ] 082
- [ ] 075
- [ ] 074
- [ ] 071
- [ ] 070
- [ ] 069
- [ ] 067
- [ ] 066
- [ ] 059
- [ ] 057
- [ ] 056
- [ ] 054
- [ ] 048
- [ ] 046
- [ ] 045
- [ ] 033
- [ ] 031
- [ ] 027
- [ ] 023
- [ ] 020
- [ ] 014
- [ ] 005
- [ ] 004
- [ ] 003
- [ ] 001

I will write a crawler to create gists for them. Later another list for refining when it's done.

**Comment by somarlyonks** [comment]
[script gist](https://gist.github.com/somarlyonks/bc340a820bc27bc9340cac241f72dcc4)

**Comment by somarlyonks** [comment]
Refine task:

- [ ] 221
- [ ] 220
- [ ] 218
- [ ] 217
- [ ] 215
- [ ] 214
- [ ] 213
- [ ] 209
- [ ] 207
- [ ] 203
- [ ] 201
- [ ] 198
- [ ] 193
- [ ] 184
- [ ] 181
- [ ] 179
- [ ] 177
- [ ] 176
- [ ] 173
- [ ] 171
- [ ] 159
- [ ] 153
- [ ] 152
- [ ] 151
- [ ] 145
- [ ] 143
- [ ] 142
- [ ] 139
- [ ] 137
- [ ] 135
- [ ] 130
- [ ] 127
- [ ] 122
- [ ] 120
- [ ] 118
- [ ] 113
- [ ] 111
- [ ] 107
- [ ] 105
- [ ] 104
- [ ] 103
- [ ] 102
- [ ] 101
- [ ] 099
- [ ] 097
- [ ] 089
- [ ] 082
- [ ] 075
- [ ] 074
- [ ] 071
- [ ] 070
- [ ] 069
- [ ] 067
- [ ] 066
- [ ] 059
- [ ] 057
- [ ] 056
- [ ] 054
- [ ] 048
- [ ] 046
- [ ] 045
- [ ] 033
- [ ] 031
- [ ] 027
- [ ] 023
- [ ] 020
- [ ] 014
- [ ] 005
- [ ] 004
- [ ] 003
- [ ] 001

**Comment by somarlyonks** [comment]
Refine task:

- [x] [221](https://gist.github.com/csszen/eb236c1ca973a1fe12e32ef67e4f500b) - ['Mid Century Modern'](https://czg.vercel.app/theme/eb236c1ca973a1fe12e32ef67e4f500b/index.html), by Andrew Lohman, http://www.andrewlohman.com/
- [x] [220](https://gist.github.com/csszen/71d17f307d1d5481e280c9ee3739bf1c) - ['Garments'](https://czg.vercel.app/theme/71d17f307d1d5481e280c9ee3739bf1c), by Dan Mall, http://www.danielmall.com
- [x] [218](https://gist.github.com/csszen/bf89eb88a71f2469e6617a6a238a853e) - ['Apothecary'](https://czg.vercel.app/theme/bf89eb88a71f2469e6617a6a238a853e), by Trent Walton, http://www.trentwalton.com/
- [x] [217](https://gist.github.com/csszen/f4b657c4e3b99c63281b079f66d4dc34) - ['Screen Filler'](https://czg.vercel.app/theme/f4b657c4e3b99c63281b079f66d4dc34), by Elliot Jay Stocks, http://elliotjaystocks.com
- [x] [215](https://gist.github.com/csszen/5486806e35e68e5e001940ff35b11b37) - ['A Robot Named Jimmy'](https://czg.vercel.app/theme/5486806e35e68e5e001940ff35b11b37), by meltmedia, http://meltmedia.com
- [x] [214](https://gist.github.com/csszen/0cd42d60c4a895d1989f836a44e6586f) - ['Verde Moderna'](https://czg.vercel.app/theme/0cd42d60c4a895d1989f836a44e6586f/index.html), by Dave Shea, http://www.mezzoblue.com/
- [x] [213](https://gist.github.com/csszen/4e078b542f6c47539d3d39ec4a2ced5b) - ['Under the Sea'](https://czg.vercel.app/theme/4e078b542f6c47539d3d39ec4a2ced5b/index.html), by Eric Stoltz, http://www.ericstoltz.com/
- [x] [209](https://gist.github.com/csszen/8c90e0fccbe6c4f6feeed3680a164c5f) - ['CSS Co., Ltd.'](https://czg.vercel.app/theme/8c90e0fccbe6c4f6feeed3680a164c5f/index.html), by Benjamin Klemm, http://www.re-bloom.com/
- [x] [207](https://gist.github.com/csszen/37d5acb9a5634faa698fe4516cf28735) - ['Kyoto Forest'](https://czg.vercel.app/theme/37d5acb9a5634faa698fe4516cf28735/index.html), by John Politowski, http://rpmdesignfactory.com/
- [x] [203](https://gist.github.com/csszen/95ee9224a34ef203d7196375a021f666) - ['Tiny Blue'](https://czg.vercel.app/theme/95ee9224a34ef203d7196375a021f666/index.html), by Timo Virtanen, http://www.timovirtanen.com/
- [x] [201](https://gist.github.com/csszen/c56482fa612d02a300d23a4114372b91) - ['Lily Pond'](https://czg.vercel.app/theme/c56482fa612d02a300d23a4114372b91/index.html), by Rose Thorogood, http://tulips4rose.com/
- [x] [198](https://gist.github.com/csszen/daaddafadc99172ece0350fcf42e7c86) - ['The Original'](https://czg.vercel.app/theme/daaddafadc99172ece0350fcf42e7c86/index.html), by Joachim Shotter, http://www.bluejam.com/
- [x] [193](https://gist.github.com/csszen/3d4e81447f6d5805d07253752130c042) - ['Leggo My Ego'](https://czg.vercel.app/theme/3d4e81447f6d5805d07253752130c042/index.html), by Jon Tan, http://www.gr0w.com/
- [x] [184](https://gist.github.com/csszen/65ede53693d3e7e6befdd517a5fc4def) - ['Peace of Mind'](https://czg.vercel.app/theme/65ede53693d3e7e6befdd517a5fc4def/index.html), by Carlos Varela, http://www.carlosvarela.net/
- [x] [181](https://gist.github.com/csszen/5fd5f3e5b8d59ab0a82d18b2f43572cb) - ['Pretty in Pink'](https://czg.vercel.app/theme/5fd5f3e5b8d59ab0a82d18b2f43572cb/index.html), by Jordi Romkema, http://www.jor-on.com/
- [x] [179](https://gist.github.com/csszen/82b2af0425aeeeaa4504daf5009be144) - ['Vin Rouge'](https://czg.vercel.app/theme/4295faf12985863fb730cd5cafce6b5d), by Thorsten Bopp, http://www.bopp-medien.de/
- [x] [177](https://gist.github.com/csszen/5b09462b2d238fc54c3c691897722d20) - ['Zen City Morning'](https://czg.vercel.app/theme/5b09462b2d238fc54c3c691897722d20/index.html), by Ray Henry, http://www.reh3.com/
- [x] [176](https://gist.github.com/csszen/91ac03db40f3d0d90a672341df0eca0d) - ['Kelmscott'](https://czg.vercel.app/theme/91ac03db40f3d0d90a672341df0eca0d/index.html), by Bronwen Hodgkinson, http://www.cdevision.com/
- [x] [173](https://gist.github.com/csszen/e2e8c542c161f21866a4217968862fbf) - ['Red Stars'](https://czg.vercel.app/theme/e2e8c542c161f21866a4217968862fbf/index.html), by Shafiq Rizwan, http://www.1988online.net/
- [x] [171](https://gist.github.com/csszen/7fcd1af0401e6931325bbbe0d3cabb2a) - ['Shaolin Yokobue'](https://czg.vercel.app/theme/7fcd1af0401e6931325bbbe0d3cabb2a/index.html), by Javier Cabrera, http://www.emaginacion.com.ar/hacks/
- [x] [159](https://gist.github.com/csszen/5e31336dbb5cfda86f91f4e4f4b6376e) - ['Berry Flavour'](https://czg.vercel.app/theme/5e31336dbb5cfda86f91f4e4f4b6376e/index.html), by Maren Becker, http://www.honeyjazz.net/
- [x] [153](https://gist.github.com/csszen/975df90f53647b1320a1948e047392f4) - ['Moss'](https://czg.vercel.app/theme/975df90f53647b1320a1948e047392f4/index.html), by Mani Sheriar, http://www.manisheriar.com/
- [x] [152](https://gist.github.com/csszen/b2a9f994236fe827651593e73a88f4a4) - ['Subway Dream'](https://czg.vercel.app/theme/b2a9f994236fe827651593e73a88f4a4/index.html), by Pablo Caro, http://www.nuevostudio.com/
- [x] [151](https://gist.github.com/csszen/179c7fdb57cf7d489e1d15e4c2ffe6b9) - ['Contempo Finery'](https://czg.vercel.app/theme/179c7fdb57cf7d489e1d15e4c2ffe6b9), by Ro London, http://www.intersmash.com/
- [x] [145](https://gist.github.com/csszen/a841a0e5d6c7c2ebbcc0a4f3fa163b2a) - ['Paravion'](https://czg.vercel.app/theme/a841a0e5d6c7c2ebbcc0a4f3fa163b2a/index.html), by Emiliano Pennisi, http://www.peamarte.it/01/metro.html
- [x] [143](https://gist.github.com/csszen/559df657d514a9257fbd93d5496b748f) - ['Pixelisation'](https://czg.vercel.app/theme/559df657d514a9257fbd93d5496b748f/index.html), by Lim Yuan Qing, http://yuanqing.blogspot.com/
- [x] [142](https://gist.github.com/csszen/bfd3129d104b44706d41045d72d7ac41) - ['Invasion of the Body Switchers'](https://czg.vercel.app/theme/bfd3129d104b44706d41045d72d7ac41/index.html), by Andy Clarke, by http://www.stuffandnonsense.co.uk/
- [x] [139](https://gist.github.com/csszen/8c5158a6f96dc5649ad0dde12b7003f5) - ['Neat & Tidy'](https://czg.vercel.app/theme/8c5158a6f96dc5649ad0dde12b7003f5/index.html), by Oli Dale, http://www.designerstalk.com/
- [x] [137](https://gist.github.com/csszen/c50546cbd304c9c7f30eceea09d82894) - ['DJ Style'](https://czg.vercel.app/theme/c50546cbd304c9c7f30eceea09d82894/index.html), by Ramon Bispo, http://ilhasol.com/bastidores.asp
- [x] [135](https://gist.github.com/csszen/dde7fa0f029f45ba03fae488fbe5c6dd) - ['contemporary nouveau'](https://czg.vercel.app/theme/dde7fa0f029f45ba03fae488fbe5c6dd/index.html), by David Hellsing, http://www.monc.se/
- [x] [130](https://gist.github.com/csszen/2e6d02a7870398850655114782710def) - ['Pseudo-Sahara'](https://czg.vercel.app/theme/2e6d02a7870398850655114782710def/index.html), by John Barrick, http://www.waycoolwebdesign.com/
- [x] [122](https://gist.github.com/csszen/9a864b4af717997dd207e02f73b77df8) - ['Centerfold'](https://czg.vercel.app/theme/9a864b4af717997dd207e02f73b77df8/index.html), by John Oxton, http://joshuaink.com/
- [x] [120](https://gist.github.com/csszen/3700ece8e442b1430912b55f1255dda0) - ['Medioevo'](https://czg.vercel.app/theme/3700ece8e442b1430912b55f1255dda0/index.html), by Emiliano Pennisi, http://www.peamarte.it/01/metro.html
- [x] [118](https://gist.github.com/csszen/ce3e5a8a53248fc5b627c5c9f1660011) - ['Some Leafs'](https://czg.vercel.app/theme/ce3e5a8a53248fc5b627c5c9f1660011/index.html), by Michael Tupy, http://www.t-2.at/
- [x] [113](https://gist.github.com/csszen/07d08547c373be0842dddbb4257ece18) - ['Switch On'](https://czg.vercel.app/theme/07d08547c373be0842dddbb4257ece18/index.html), by Michael Fasani, http://www.michaelfasani.com/
- [x] [111](https://gist.github.com/csszen/8be4c2947f4054408a220edbfca9f20f) - ['Gruener Entwurf'](https://czg.vercel.app/theme/8be4c2947f4054408a220edbfca9f20f), by Hannah F. Liesong, http://www.liesong.de/
- [x] [107](https://gist.github.com/csszen/ab58808a02adc93d9fc7f05d65b868ff) - ['Defiance'](https://czg.vercel.app/theme/ab58808a02adc93d9fc7f05d65b868ff/index.html), by Angelo Paralos, http://www.ehlydesign.com/
- [x] [105](https://gist.github.com/csszen/c13fc15e9f1261999c0caa96ac59e521) - ['Austrian's Dark Side'](https://czg.vercel.app/theme/c13fc15e9f1261999c0caa96ac59e521/index.html), by Rene Grassegger, http://www.grassegger.at/
- [x] [104](https://gist.github.com/csszen/e24a05040b2b7b51396437e9b7bfb17e) - ['Invitation'](https://czg.vercel.app/theme/e24a05040b2b7b51396437e9b7bfb17e/index.html), by Brad Dailey, http://bradleyboy.com/
- [x] [103](https://gist.github.com/csszen/588160baeca32c13560ff9e3c93c3927) - ['Odyssey'](https://czg.vercel.app/theme/588160baeca32c13560ff9e3c93c3927/index.html), by Terrence Conley, http://www.liquidarch.com/
- [x] [102](https://gist.github.com/csszen/65753d5efb5ae45e82ea0d878d2b57c4) - ['Revolution!'](https://czg.vercel.app/theme/65753d5efb5ae45e82ea0d878d2b57c4/index.html), by David Hellsing, http://www.monc.se/
- [x] [101](https://gist.github.com/csszen/d1b13177d6cf56182e8882bca9dd3f1d) - ['punkass'](https://czg.vercel.app/theme/d1b13177d6cf56182e8882bca9dd3f1d), by Mikhel Proulx, http://www.mikhel.com/
- [x] [099](https://gist.github.com/csszen/238bbbaeded7db49ec9d7e5104e1eb3f) - ['Wiggles the Wonderworm'](https://czg.vercel.app/theme/238bbbaeded7db49ec9d7e5104e1eb3f/index.html), by Joseph Pearson, http://www.make
- [x] [097](https://gist.github.com/csszen/667107f92edde76170ff6524c1d2ecb4) - ['No Frontiers!'](https://czg.vercel.app/theme/667107f92edde76170ff6524c1d2ecb4/index.html), by Michal Mokrzycki, http://hyperreal.info/bhang/
- [x] [089](https://gist.github.com/csszen/5bbae2c82e6d529371abfdcd1f37f77b) - ['Dark Industrial'](https://czg.vercel.app/theme/5bbae2c82e6d529371abfdcd1f37f77b/index.html), by Ray Henry, http://www.reh3.com
- [x] [082](https://gist.github.com/csszen/60f9022669bb38a86840d91090fd0db9)  - ['Miracle Cure'](https://czg.vercel.app/theme/60f9022669bb38a86840d91090fd0db9/index.html), by Joseph Pearson, http://www.make-believe.org
- [x] [075](https://gist.github.com/csszen/1c7dcd5a72dc832dd9cba71953cf65b5) - ['Lost HighWay'](https://czg.vercel.app/theme/1c7dcd5a72dc832dd9cba71953cf65b5/index.html), by Julien Roumagnac, http://www.j-roumagnac.net/
- [x] [074](https://gist.github.com/csszen/de06c5b8a638bf2a37e0db9a9410e2b4) - ['Egyptian Dawn'](https://czg.vercel.app/theme/de06c5b8a638bf2a37e0db9a9410e2b4/index.html), by James Abbott, http://www.ja-consultancy.co.uk/
- [x] [071](https://gist.github.com/csszen/0b1fec7b370bbba6c2f4173e1ca6b453) - ['Garden Party'](https://czg.vercel.app/theme/48cad5038513237ee3511132f1e5f57f/index.html), by Bobby van der Sluis, http://www.bobbyvandersluis.com
- [x] [070](https://gist.github.com/csszen/11f3d57725e15c4cca5c1671a3ae7ec6) - ['CS(S) Monk'](https://czg.vercel.app/theme/11f3d57725e15c4cca5c1671a3ae7ec6/index.html), by Cedric Savarese, http://www.4213miles.com/
- [x] [069](https://gist.github.com/csszen/d7592c74845b96ffc472e228cc4d130d) - ['Bonsai Sky'](https://czg.vercel.app/theme/d7592c74845b96ffc472e228cc4d130d), by Mike Davidson, http://www.mdavidson.com/
- [x] [067](https://gist.github.com/csszen/b91d9f75eda46a38e63f58a399eaba31) - ['A Silent Strength'](https://czg.vercel.app/theme/b91d9f75eda46a38e63f58a399eaba31/index.html), by Ray Henry, http://www.reh3.com/
- [x] [066](https://gist.github.com/csszen/c23a1e8883377439fc0597b6868ad57d) - ['Focus & Shoot'](https://czg.vercel.app/theme/c23a1e8883377439fc0597b6868ad57d/index.html), by Colectivo YTW (Julio Beamonte, Beatriz Martinez, Gustavo Gavan, Franck Scipion), http://www.yatienesweb.info/corporativo/
- [x] [059](https://gist.github.com/csszen/9605340419bff26dbf8962db5fc8e024) - ['Dune Temple'](https://czg.vercel.app/theme/9605340419bff26dbf8962db5fc8e024/index.html), by Greg Reimer, http://www.drpeterjones.com/
- [x] [057](https://gist.github.com/csszen/269bfc799483c0f001ae84468f7ca475) - ['This is Cereal'](https://czg.vercel.app/theme/269bfc799483c0f001ae84468f7ca475/index.html), by Shaun Inman, http://www.shauninman.com/
- [x] [056](https://gist.github.com/csszen/363cb7143d9f04fa0c0c8eb569704a98) - ['Elevation'](https://czg.vercel.app/theme/363cb7143d9f04fa0c0c8eb569704a98/index.html), by Nigel Goodfellow, http://www.beforethedog.com/
- [x] [054](https://gist.github.com/csszen/f97ec24fedde7273b9a83ce16ba8bc18) - ['Gecko's Eye'](https://czg.vercel.app/theme/f97ec24fedde7273b9a83ce16ba8bc18/index.html), by Sandra Greco, http://www.magritte.it/
- [x] [048](https://gist.github.com/csszen/ce9ba93a237a78299dbb0d96b3d98fc0) - ['HoriZental'](https://czg.vercel.app/theme/ce9ba93a237a78299dbb0d96b3d98fc0), by Clément ‘fastclemmy’ Hardouin, http://www.fastclemmy.com/
- [x] [046](https://gist.github.com/csszen/99f41d4e72bba89b5a7eee79756b6fe7) - ['sub:lime'](https://czg.vercel.app/theme/99f41d4e72bba89b5a7eee79756b6fe7/index.html), by Andy Budd, http://www.andybudd.com/blog/
- [x] [045](https://gist.github.com/csszen/94ee68e1c4af3439fbe1fd90eb60985f) - ['I Dream in Colour'](https://czg.vercel.app/theme/94ee68e1c4af3439fbe1fd90eb60985f/index.html), by Jeff Bilen, http://www.scribblersclub.com/
- [x] [033](https://gist.github.com/csszen/53bc7af4fad3279bc7cedcb3fdc1a543) - ['Fleur-de-lys'](https://czg.vercel.app/theme/53bc7af4fad3279bc7cedcb3fdc1a543/index.html), by Claire Campbell, http://www.tanfa.designer-nameo.uk/
- [x] [031](https://gist.github.com/csszen/2c770108b4212d44924fa0b2ff783cdb) - ['Hedges'](https://czg.vercel.app/theme/2c770108b4212d44924fa0b2ff783cdb/index.html), by Kev Mears, http://www.mearso.com/
- [x] [027](https://gist.github.com/csszen/9dfcfe746c64e277f5a23b4371f4da9b) - ['Gothica'](https://czg.vercel.app/theme/9dfcfe746c64e277f5a23b4371f4da9b/index.html), by Patrick H. Lauke aka redux, http://redux.deviantart.com/
- [x] [023](https://gist.github.com/csszen/02c4b112700791ea1ec112c09b664b48) - ['fleur de l'avant-garde'](https://czg.vercel.app/theme/02c4b112700791ea1ec112c09b664b48/index.html), by Michael Switzer, http://propagandabydesign.com/
- [x] [020](https://gist.github.com/csszen/7f87f1574031fe4a959c0021b67bb0a1) - ['Friendly Beaches'](https://czg.vercel.app/theme/7f87f1574031fe4a959c0021b67bb0a1/index.html), by Sophie G, http://www.sophie-g.net
- [x] [014](https://gist.github.com/csszen/749e104ab93984ec8859f5bcabdcd7fc) - ['Samuraai'](https://czg.vercel.app/theme/749e104ab93984ec8859f5bcabdcd7fc/index.html), by Minz Meyer, by http://www.minzweb.de/
- [x] [005](https://gist.github.com/csszen/b987c132842fc34c895b18d5be280a33) - ['Blood Lust'](https://czg.vercel.app/theme/b987c132842fc34c895b18d5be280a33/index.html), by Dave Shea', http://www.mezzoblue.com/
- [x] [004](https://gist.github.com/csszen/7a990163955bca4f324ccb74327580b9) - ['arch4.20'](https://czg.vercel.app/theme/7a990163955bca4f324ccb74327580b9/index.html), by Dave Shea, http://www.mezzoblue.com/
- [x] [003](https://gist.github.com/csszen/ca9abcf6d82ecafbc8679321b0f0ae25) - ['Stormweather'](https://czg.vercel.app/theme/ca9abcf6d82ecafbc8679321b0f0ae25/index.html), by Dave Shea, http://www.mezzoblue.com/
- [x] [001](https://gist.github.com/csszen/9afb92b518c6a663e531d45992075de8) - ['Tranquille'](https://czg.vercel.app/theme/c6ab851c3a08f34de8dad89c3e9d2763/index.html) by Dave Shea - http://www.mezzoblue.com/

**Comment by somarlyonks** [comment]
@csszen better to redeploy the site.
